import { useState, useEffect } from 'react';

// ── Asset paths ──────────────────────────────────────────────────────────────
// Resolved once via IPC so they work in both dev (localhost) and prod (file://)
export let ICON_MASS   = '';
export let ICON_ENERGY = '';
export let ICON_ACU    = '';  // ACU_Spawn.png — desaturated generic
export const ICON_ACU_ARMY = Array(16).fill(''); // ARMY_1.png … ARMY_16.png

window.electronAPI.invoke('get-asset-base-url').then(({ baseUrl }) => {
  ICON_MASS   = baseUrl + '/assets/icons/Library/mass.png';
  ICON_ENERGY = baseUrl + '/assets/icons/Library/energy.png';
  ICON_ACU    = baseUrl + '/assets/ACU/ACU_Spawn.png';
  for (let i = 0; i < 16; i++) {
    ICON_ACU_ARMY[i] = baseUrl + `/assets/ACU/ARMY_${i+1}.png`;
  }
}).catch(() => {
  ICON_MASS   = '/assets/icons/Library/mass.png';
  ICON_ENERGY = '/assets/icons/Library/energy.png';
  ICON_ACU    = '/assets/ACU/ACU_Spawn.png';
  for (let i = 0; i < 16; i++) {
    ICON_ACU_ARMY[i] = `/assets/ACU/ARMY_${i+1}.png`;
  }
});

// Returns the per-army coloured icon, fallback to generic ACU_SPAWN
export const getAcuIcon = idx => ICON_ACU_ARMY[idx] || ICON_ACU;

// ── Icon loader hook ─────────────────────────────────────────────────────────
// Forces a re-render once the async IPC icon URLs have resolved
export function useIconsReady() {
  const [ready, setReady] = useState(ICON_MASS !== '');
  useEffect(() => {
    if (ICON_MASS !== '') { setReady(true); return; }
    const id = setInterval(() => { if (ICON_MASS !== '') { setReady(true); clearInterval(id); } }, 50);
    return () => clearInterval(id);
  }, []);
  return ready;
}

// ── ACU colour filter ─────────────────────────────────────────────────────────
// Converts a hex colour to a CSS filter string that tints the white ACU icon.
// Strategy: brightness(0) → colour via sepia+hue-rotate+saturate.
export function acuColorFilter(hex) {
  // Robust tinting: make image white first, then apply colour via drop-shadow.
  // Works on any image regardless of original colours.
  // 1. brightness(0) invert(1)  → pure white
  // 2. sepia+hue-rotate+saturate → target colour
  const r = parseInt(hex.slice(1,3),16)/255;
  const g = parseInt(hex.slice(3,5),16)/255;
  const b = parseInt(hex.slice(5,7),16)/255;
  const max=Math.max(r,g,b), min=Math.min(r,g,b), d=max-min;
  let h=0;
  if(d>0){
    if(max===r) h=((g-b)/d+6)%6;
    else if(max===g) h=(b-r)/d+2;
    else h=(r-g)/d+4;
    h*=60;
  }
  const s   = max===0 ? 0 : d/max;
  const hueRot = Math.round(h - 36);          // sepia baseline ≈ 36°
  const sat    = Math.max(1, Math.round(s * 900));
  const br     = Math.max(50, Math.round(max * 200));
  return `brightness(0) invert(1) sepia(1) saturate(${sat}%) hue-rotate(${hueRot}deg) brightness(${br}%)`;
}

// ── Lua Parser ───────────────────────────────────────────────────────────────
// Searches the entire source for named markers that have a position field.
// This avoids the old two-step approach (markerBlock regex → entryRe) which
// silently dropped the last marker in the file when its closing } coincided
// with the lookahead terminator of the outer regex.
export function parseSaveLua(src) {
  const armies = {}, mass = {}, hydro = {};
  // Match every named marker that contains a position — works regardless of
  // where the marker sits in the file (first, last, or middle).
  const entryRe = /\['([^']+)'\]\s*=\s*\{[\s\S]*?position'\]\s*=\s*VECTOR3\(\s*([\d.]+),\s*[\d.]+,\s*([\d.]+)\s*\)/g;
  let m;
  while ((m = entryRe.exec(src)) !== null) {
    const name = m[1];
    const x = parseFloat(m[2]), y = parseFloat(m[3]);
    if      (name.match(/^ARMY_\d+$/))    armies[name] = { x, y };
    else if (name.startsWith('Mass '))    mass[name.replace('Mass ','').trim()]            = { x, y };
    else if (name.startsWith('Hydrocarbon ')) hydro[name.replace('Hydrocarbon ','').trim()] = { x, y };
  }
  return { armies, mass, hydro };
}

// ── Constants ────────────────────────────────────────────────────────────────
// Exact colours from Photopea — matches ARMY_1.png … ARMY_16.png
export const ARMY_COLORS = [
  '#ef0808', //  1  Red
  '#941421', //  2  Dark Red
  '#ff8639', //  3  Orange
  '#b56518', //  4  Dark Orange
  '#a59600', //  5  Olive
  '#fffb00', //  6  Yellow
  '#9cdb00', //  7  Yellow-Green
  '#42be42', //  8  Green
  '#298a52', //  9  Teal-Green
  '#294d4a', // 10  Dark Teal
  '#426def', // 11  Cornflower Blue
  '#2928e7', // 12  Blue
  '#5a00a5', // 13  Purple
  '#9461ff', // 14  Lavender
  '#63ffce', // 15  Cyan-Mint
  '#ff8aff', // 16  Pink
];

export const ALL_TYPE_META = {
  spawnMex:   { label:'Spawn Mex',   color:'#64b5f6' },
  spawnHydro: { label:'Spawn Hydro', color:'#81c784' },
};

// ── Options Generator ─────────────────────────────────────────────────────────
export function generateOptionsLua() {
  return `--[[  Generated by ForgeMapToolkit - Adaptive Map Helper  ]]--

options ={

{
    default = 1,
    label = "<LOC adaptive_dynamic_spawn_label> Dynamic Spawn Of Resources",
    help = "<LOC adaptive_dynamic_spawn_help> Determine which mexes & hydros should be spawned.",
    key = 'dynamic_spawn',
    pref = 'dynamic_spawn',
    values = {
        { text = "<LOC adaptive_dynamic_spawn_key_1_label> mirror slots", help = "<LOC adaptive_dynamic_spawn_key_1_help> Spawn resources for player & mirror slot (balanced resources).", key = 1, },
        { text = "<LOC adaptive_dynamic_spawn_key_2_label> used slots", help = "<LOC adaptive_dynamic_spawn_key_2_help> Only spawn resources for player on used slots (unbalanced resources).", key = 2, },
        { text = "<LOC adaptive_dynamic_spawn_key_3_label> no mirror = no resources", help = "<LOC adaptive_dynamic_spawn_key_3_help> Only spawn resources if mirror slot is also occupied by a player.", key = 3, },
    },
},

{
    default = 1,
    label = "<LOC adaptive_crazyrush_label> Crazyrush",
    help = "<LOC adaptive_crazyrush_help> Activate different types of crazyrush for the spawned mexes.",
    key = 'crazyrush_mexes',
    pref = 'crazyrush_mexes',
    values = {
        { text = "<LOC adaptive_disabled> disabled", help = "<LOC adaptive_crazyrush_key_1_help> No crazyrush.", key = 1, },
        { text = "<LOC adaptive_crazyrush_key_4_label> crazyrush", help = "<LOC adaptive_crazyrush_key_4_help> Activate crazyrush for all spawned mexes.", key = 4, },
    },
},

};
`;
}

// ── Script Generator ──────────────────────────────────────────────────────────
export function generateScriptLua(mapName) {
  const name      = (mapName||'').trim();
  const finalName = /\.v\d{4}$/.test(name) ? name : name+'.v0001';
  // baseName must be the exact folder name without version suffix.
  // e.g. "adaptive_Tartaron.v0006" → baseName = "adaptive_Tartaron"
  // so the import path becomes /maps/adaptive_Tartaron.v0006/adaptive_Tartaron_tables.lua
  const baseName  = finalName.replace(/\.v\d{4}$/, '');
  const importPath = `/maps/${finalName}/${baseName}_tables.lua`;
  return `------------------------------------------------------------------------
----- Generated by ForgeMapToolkit - Adaptive Map Helper            -----
------------------------------------------------------------------------
local ScenarioUtils = import('/lua/sim/ScenarioUtilities.lua')
local ScenarioFramework = import('/lua/ScenarioFramework.lua')
local Tables = import('${importPath}')

------------------------------------------------------------------------
----- Options ----------------------------------------------------------
------------------------------------------------------------------------
local maxPlayerOnMap  = Tables.maxPlayerOnMap or 16
local dynamic_spawn   = ScenarioInfo.Options.dynamic_spawn   or 1
local crazyrush_mexes = ScenarioInfo.Options.crazyrush_mexes or 1

------------------------------------------------------------------------
----- Crazyrush state --------------------------------------------------
------------------------------------------------------------------------
local spawnedMassSpots = {}
local spawnedMexNumber = 0
local currentResSpot   = 0
local generatedMass    = {}
local checkedExtractor = {}
local MexList          = {}
math.randomseed(1)

------------------------------------------------------------------------
----- Initialization ---------------------------------------------------
------------------------------------------------------------------------
function OnPopulate()
    LOG("ADAPTIVE: OnPopulate")
    ScenarioUtils.InitializeArmies()
end

function OnStart()
    LOG("ADAPTIVE: OnStart")
    if crazyrush_mexes > 1 then
        ForkThread(Crazyrush_checkMassPoint)
    end
end

------------------------------------------------------------------------
----- Dynamic resource spawning ----------------------------------------
------------------------------------------------------------------------
-- Overrides the engine default. Decides which Mass/Hydro markers spawn
-- based on which armies are present and the dynamic_spawn option.
function ScenarioUtils.CreateResources()
    LOG("ADAPTIVE: CreateResources()")

    local markers       = ScenarioUtils.GetMarkers()
    local spwnMexArmy   = Tables.spwnMexArmy   or {}
    local spwnHydroArmy = Tables.spwnHydroArmy or {}

    -- Build list of present armies: real players + lobby-selected spawn positions.
    -- SpawnMex contains positions selected via the FAF close-spawn / position picker.
    -- A slot marked true counts as occupied even without a real player sitting there.
    local ArmyList = ListArmies()
    for j, spawnmex in ScenarioInfo.Options.SpawnMex or {} do
        if spawnmex then
            ArmyList[table.getn(ArmyList) + 1] = 'ARMY_' .. j
        end
    end

    local Notpresentarmies = {}
    local notPresentCount  = 1

    if dynamic_spawn == 1 then
        -- Mirror-slot: skip pair if neither army of the pair is present
        for m = 1, maxPlayerOnMap / 2 do
            local a1 = 2*m - 1
            local a2 = 2*m
            local present = 0
            for _, army in ArmyList do
                if army == ("ARMY_" .. a1) or army == ("ARMY_" .. a2) then
                    present = present + 1
                end
            end
            if present < 1 then
                Notpresentarmies[notPresentCount] = a1; notPresentCount = notPresentCount + 1
                Notpresentarmies[notPresentCount] = a2; notPresentCount = notPresentCount + 1
            end
        end

    elseif dynamic_spawn == 2 then
        -- Used-slots: skip each individually absent army
        for m = 1, maxPlayerOnMap do
            local found = false
            for _, army in ArmyList do
                if army == ("ARMY_" .. m) then found = true; break end
            end
            if not found then
                Notpresentarmies[notPresentCount] = m
                notPresentCount = notPresentCount + 1
            end
        end

    elseif dynamic_spawn == 3 then
        -- Strict mirror: skip both slots unless BOTH are present
        for m = 1, maxPlayerOnMap / 2 do
            local a1 = 2*m - 1
            local a2 = 2*m
            local present = 0
            for _, army in ArmyList do
                if army == ("ARMY_" .. a1) or army == ("ARMY_" .. a2) then
                    present = present + 1
                end
            end
            if present < 2 then
                Notpresentarmies[notPresentCount] = a1; notPresentCount = notPresentCount + 1
                Notpresentarmies[notPresentCount] = a2; notPresentCount = notPresentCount + 1
            end
        end
    end

    LOG("ADAPTIVE: absent army slots = ", notPresentCount - 1)

    for name, tblData in pairs(markers) do
        if tblData.resource then
            local doit = true

            -- Remove markers belonging to absent armies
            for _, armynumber in Notpresentarmies do
                doit = FalseIfInList(name, spwnMexArmy[armynumber]   or {}, MassString,  doit)
                doit = FalseIfInList(name, spwnHydroArmy[armynumber] or {}, HydroString, doit)
            end

            if doit then
                if tblData.type == 'Mass' then
                    spawnedMexNumber = spawnedMexNumber + 1
                    spawnedMassSpots[spawnedMexNumber] = name
                end
                SpawnResource(tblData.position, tblData.type)
            end
        end
    end

    LOG("ADAPTIVE: spawned ", spawnedMexNumber, " mass spots")
end

------------------------------------------------------------------------
----- Helpers ----------------------------------------------------------
------------------------------------------------------------------------
function MassString(n)
    if n > 9 then return "Mass " .. n else return "Mass 0" .. n end
end

function HydroString(n)
    if n > 9 then return "Hydrocarbon " .. n else return "Hydrocarbon 0" .. n end
end

function FalseIfInList(name, list, stringFn, _doit)
    for k = 1, table.getn(list) do
        if name == stringFn(list[k]) then return false end
    end
    return _doit
end

function SpawnResource(position, restype)
    local albedo, bp, lod, size
    if restype == 'Mass' then
        albedo = "/env/common/splats/mass_marker.dds"
        bp     = "/env/common/props/massDeposit01_prop.bp"
        lod    = 100
        size   = 2
    else
        albedo = "/env/common/splats/hydrocarbon_marker.dds"
        bp     = "/env/common/props/hydrocarbonDeposit01_prop.bp"
        lod    = 200
        size   = 6
    end
    CreateSplat(position, 0, albedo, size, size, lod, 0, -1, 0)
    CreateResourceDeposit(restype, position[1], position[2], position[3], size/2)
    CreatePropHPR(bp, position[1], position[2], position[3], Random(0, 360), 0, 0)
end

------------------------------------------------------------------------
----- Crazyrush --------------------------------------------------------
------------------------------------------------------------------------
function Crazyrush_checkMassPoint()
    while true do
        local units = GetUnitsInRect({x0=0, x1=ScenarioInfo.size[1], y0=0, y1=ScenarioInfo.size[2]})
        if units then
            for _, unit in units do
                if EntityCategoryContains(categories.MASSEXTRACTION, unit) then
                    local px = unit:GetPosition()[1]
                    local pz = unit:GetPosition()[3]
                    if not Crazyrush_alreadyChecked(px, pz) then
                        Crazyrush_TrySpawn(px - 2, pz)
                        Crazyrush_TrySpawn(px + 2, pz)
                        Crazyrush_TrySpawn(px,     pz - 2)
                        Crazyrush_TrySpawn(px,     pz + 2)
                    end
                    WaitSeconds(0.01)
                end
            end
        end
        WaitSeconds(1)
    end
end

function Crazyrush_alreadyChecked(x, y)
    if checkedExtractor[x] == nil then
        checkedExtractor[x] = {}; checkedExtractor[x][y] = true; return false
    elseif checkedExtractor[x][y] == nil then
        checkedExtractor[x][y] = true; return false
    end
    return true
end

function Crazyrush_TrySpawn(x, y)
    if generatedMass[x] and generatedMass[x][y] then return end
    if generatedMass[x] == nil then generatedMass[x] = {} end
    generatedMass[x][y] = true
    SpawnResource(VECTOR3(x, GetTerrainHeight(x,y), y), 'Mass')
    MexList[table.getn(MexList)+1] = {x, y}
end
`;
}

// ── Tables Generator ──────────────────────────────────────────────────────────
export function generateTablesLua(armyList, assignments, maxPlayers) {
  const armies = armyList.filter(a => a !== 'ARMY_17');
  const spwnMex = {}, spwnHydro = {};
  armies.forEach(a => { spwnMex[a]=[]; spwnHydro[a]=[]; });

  Object.entries(assignments).forEach(([key, { type, army }]) => {
    if      (type==='spawnMex'   && army && army!=='ARMY_17') spwnMex[army].push(key);
    else if (type==='spawnHydro' && army && army!=='ARMY_17') spwnHydro[army].push(key);
  });

  const fmtNum  = n => String(parseInt(n, 10));
  const fmtArmy = tbl => armies.map(a=>`\t\t\t\t{${(tbl[a]||[]).map(fmtNum).join(',')}}`).join(',\n');

  return `--[[  Generated by ForgeMapToolkit - Adaptive Map Helper  ]]--\n\nmaxPlayerOnMap = ${maxPlayers}\n\nspwnMexArmy = {\n${fmtArmy(spwnMex)}\n}\n\nspwnHydroArmy = {\n${fmtArmy(spwnHydro)}\n}\n`;
}
