// ─── Central README Generator ────────────────────────────────────────────────
// Shared utility for all ForgeMapToolkit tabs.
// Usage:
//   import { generateReadme } from '../../../../utils/readmeGenerator';
//
//   const content = generateReadme({
//     tool:     'Wreckage Tab',
//     mapName:  finalMapName,
//     mapSize:  '1024 × 1024 (20×20 km)',
//     sections: [
//       { title: 'OUTPUT SUMMARY', entries: [['Total placements', 42]] },
//       { title: 'UNIT CARDS',     entries: [['UEL0203', '10 placements']] },
//     ],
//     footer: [
//       'Generated by ForgeMapToolkit · Seraphim-Noob',
//       'SCMAP-Tool — original foundation by The-Balthazar',
//     ],
//   });
// ─────────────────────────────────────────────────────────────────────────────

const DIVIDER     = '─'.repeat(60);
const BOX_TOP     = '╔══════════════════════════════════════════════════════════╗';
const BOX_BOTTOM  = '╚══════════════════════════════════════════════════════════╝';

/**
 * Centre a string inside the box (58 usable chars between the │ borders).
 */
function boxLine(text) {
  const inner = 58;
  const pad   = Math.max(0, inner - text.length);
  const left  = Math.floor(pad / 2);
  const right = pad - left;
  return `║${' '.repeat(left)}${text}${' '.repeat(right)}║`;
}

/**
 * Build a timestamp object from the current date.
 */
function timestamp() {
  const now     = new Date();
  const dateStr = now.toLocaleDateString('en-GB');
  const timeStr = now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
  return { dateStr, timeStr };
}

/**
 * Generate a README string.
 *
 * @param {object} opts
 * @param {string}   opts.tool       – Tab name shown in the header and Generated line.
 * @param {string}   opts.mapName    – Map name.
 * @param {string}   opts.mapSize    – Pre-formatted map size string.
 * @param {Array}    opts.sections   – Array of { title, entries, lines? } objects.
 *   - entries: Array of [label, value] pairs → '  label : value'
 *   - lines:   Array of raw strings (used when the tab needs full control)
 * @param {string[]} [opts.footer]   – Footer lines (shown above final divider).
 *                                     Defaults to the generic ForgeMapToolkit credit.
 * @returns {string}
 */
export function generateReadme({ tool, mapName, mapSize, sections = [], footer }) {
  const { dateStr, timeStr } = timestamp();

  const lines = [];

  // ── Box header ──────────────────────────────────────────────────────────────
  lines.push(BOX_TOP);
  lines.push(boxLine(`${tool.toUpperCase()} — README`));
  lines.push(BOX_BOTTOM);
  lines.push('');

  // ── Meta ────────────────────────────────────────────────────────────────────
  lines.push(`  Generated  : ${dateStr} at ${timeStr}`);
  lines.push(`  Tool       : ForgeMapToolkit — ${tool}`);
  lines.push('');

  // ── Map settings ────────────────────────────────────────────────────────────
  lines.push(DIVIDER);
  lines.push('  MAP SETTINGS');
  lines.push(DIVIDER);
  lines.push(`  Map Name   : ${mapName}`);
  lines.push(`  Map Size   : ${mapSize}`);
  lines.push('');

  // ── Tab-specific sections ───────────────────────────────────────────────────
  for (const section of sections) {
    lines.push(DIVIDER);
    lines.push(`  ${section.title}`);
    lines.push(DIVIDER);

    if (section.entries) {
      for (const [label, value] of section.entries) {
        lines.push(`  ${label} : ${value}`);
      }
    }

    if (section.lines) {
      for (const line of section.lines) {
        lines.push(line);
      }
    }

    lines.push('');
  }

  // ── Footer ──────────────────────────────────────────────────────────────────
  lines.push(DIVIDER);
  if (footer && footer.length > 0) {
    for (const line of footer) lines.push(`  ${line}`);
  } else {
    lines.push('  Generated by ForgeMapToolkit · Seraphim-Noob');
    lines.push('  https://github.com/ForgeMapToolKit/ForgeMapToolkit');
  }
  lines.push(DIVIDER);

  return lines.join('\n');
}

/**
 * Convenience: write the README to disk via the Electron IPC helper.
 * Throws if the write fails.
 *
 * @param {string} filePath   – Full absolute path.
 * @param {string} content    – Content returned by generateReadme().
 */
export async function writeReadme(filePath, content) {
  const r = await window.electronAPI.invoke('write-file', { filePath, content });
  if (!r?.success) throw new Error(r?.error || 'write-file failed');
}
