// ═══════════════════════════════════════════════════════════════════════════════
// GUIDE DATA — ForgeMapToolkit Guide Section
// ═══════════════════════════════════════════════════════════════════════════════
//
// Guide shape:
//   id          — unique string
//   category    — matches a GUIDE_CATEGORIES id
//   status      — 'available' | 'planned'
//   title       — display title
//   abstract    — short description shown in cards/featured
//   author      — string | null
//   thumb       — repo-relative path to a preview image, e.g. 'water/overview-thumb.png'
//                 falls back to the category thumbnail if null
//   htmlFile    — repo-relative path to the .html guide file (local guides only), string | null
//   videoUrl    — YouTube URL | null  (renders a Video tab alongside the guide text)
//   externalUrl — link for non-local guides (wiki, forum, etc.) | null
//   _urlPending — true if externalUrl / videoUrl still needs to be filled in
//
// NOTE: All guides will eventually be local. External links (wiki, forum) are
// kept only as supplementary references until the local version is written.
// ═══════════════════════════════════════════════════════════════════════════════

export const GUIDE_CATEGORIES = [
    {
    id: 'FAFMapEditor',
    label: 'FAF Map Editor',
    color: '#7CFF6B',
    glow: 'rgba(124,255,107,0.25)',
    glowStrong: 'rgba(124,255,107,0.5)',
    description: 'Map Editor',
  },
  {
    id: 'editors',
    label: 'Editors & Tools',
    color: '#00C8FF',
    glow: 'rgba(0,200,255,0.25)',
    glowStrong: 'rgba(0,200,255,0.5)',
    description: 'Map editors, setup guides and video tutorials.',
  },
  {
    id: 'terrain',
    label: 'Terrain & General',
    color: '#7CFF6B',
    glow: 'rgba(124,255,107,0.25)',
    glowStrong: 'rgba(124,255,107,0.5)',
    description: 'Map design fundamentals, terrain theory and general mapping guides.',
  },
  {
    id: 'gaea',
    label: 'Gaea',
    color: '#ffb700',
    glow: 'rgba(255,183,0,0.25)',
    glowStrong: 'rgba(255,183,0,0.5)',
    description: 'Terrain generation with Gaea — heightmaps, masks and texturing.',
  },
  {
    id: 'water',
    label: 'Water',
    color: '#00AAFF',
    glow: 'rgba(0,170,255,0.25)',
    glowStrong: 'rgba(0,170,255,0.5)',
    description: 'Complete water system series — settings, waves, ramps and environment maps.',
  },
  {
    id: 'decals',
    label: 'Decals',
    color: '#FF9A3C',
    glow: 'rgba(255,154,60,0.25)',
    glowStrong: 'rgba(255,154,60,0.5)',
    description: 'Decal creation and workflow — normal maps, WorldMachine templates and map-wide textures.',
  },
  {
    id: 'ai',
    label: 'AI & Markers',
    color: '#FF4F4F',
    glow: 'rgba(255,79,79,0.25)',
    glowStrong: 'rgba(255,79,79,0.5)',
    description: 'AI marker placement and pathing for maps.',
  },
  {
    id: 'adaptive',
    label: 'Adaptive Maps',
    color: '#FFD700',
    glow: 'rgba(255,215,0,0.25)',
    glowStrong: 'rgba(255,215,0,0.5)',
    description: 'Creating adaptive maps with dynamic scripting.',
  },
  {
    id: 'skybox',
    label: 'Skybox',
    color: '#FF8AFF',
    glow: 'rgba(255,138,255,0.25)',
    glowStrong: 'rgba(255,138,255,0.5)',
    description: 'Skybox setup and configuration guides.',
  },
  {
    id: 'coop',
    label: 'Co-op & Campaign',
    color: '#00E5CC',
    glow: 'rgba(0,229,204,0.25)',
    glowStrong: 'rgba(0,229,204,0.5)',
    description: 'Maps and content for campaign and co-op missions.',
  },
  {
    id: 'foundations',
    label: 'Foundation Guides',
    color: '#FF6B6B',
    glow: 'rgba(255,107,107,0.25)',
    glowStrong: 'rgba(255,107,107,0.5)',
    description: 'Core concepts, rules, and references that underpin everything else, from vault requirements to shader fundamentals.',
  },
  {
    id: 'gameplay',
    label: 'Gameplay-Driven Mapping',
    color: '#A855F7',
    glow: 'rgba(168,85,247,0.25)',
    glowStrong: 'rgba(168,85,247,0.5)',
    description: 'Design decisions that make a map play well — mass layout, balance, terrain flow and competitive structure.',
  },
];


export const GUIDES = [

  // ── FAF Map Editor ──────────────────────────────────────────────────────────
    {
    id: 'g01',
    category: 'FAFMapEditor',
    status: 'available',
    title: 'Getting Started',
    abstract: 'Getting Started covers everything you need to go from zero to a running editor. You will learn where to download the editor, how to install it, and what each setting in the Preferences menu does. By the end of this section, your editor is fully configured and ready to use.',
    author: 'Seraphim-Noob',
    thumb: null,
    htmlFile: 'FAFMapEditor/getting_started.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g02',
    category: 'FAFMapEditor',
    status: 'available',
    title: 'Create a new map',
    abstract: 'Covers the Create New Map dialog — name, type, player count, and size.',
    author: 'Seraphim-Noob',
    thumb: null,
    htmlFile: 'FAFMapEditor/creating_a_new_map.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g03',
    category: 'FAFMapEditor',
    status: 'available',
    title: 'Editor Overview',
    abstract: 'This guide covers the overall structure of the FA Forever Map Editor, including the menubar and all its options, the tab panel, the viewport, and the coordinate display.',
    author: 'Seraphim-Noob',
    thumb: null,
    htmlFile: 'FAFMapEditor/editor_overview.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g04',
    category: 'FAFMapEditor',
    status: 'available',
    title: 'The Map Tab',
    abstract: ' This guide walks you through all three of its sub-tabs (General, Armies, and Areas), covering everything from its name, how to add new spawns to defining your maps playable boundaries.',
    author: 'Seraphim-Noob',
    thumb: null,
    htmlFile: 'FAFMapEditor/maptab.html',
    videoUrl: null,
    externalUrl: null,
  },
  // ── Terrain & General ────────────────────────────────────────────────────────
  {
    id: 'g12',
    category: 'terrain',
    status: 'available',
    title: 'Mapping General',
    abstract: 'Overview and entry point for all mapping topics on the FAF wiki.',
    author: null,
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://wiki.faforever.com/en/Development/Mapping',
  },
  {
    id: 'g13',
    category: 'terrain',
    status: 'available',
    title: 'Terminology / Glossary',
    abstract: 'Reference glossary of mapping terms used across FAF documentation.',
    author: null,
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://wiki.faforever.com/en/Development/Mapping/Terms',
  },
  {
    id: 'g14',
    category: 'terrain',
    status: 'available',
    title: 'FAF Terrain Shaders',
    abstract: 'Deep dive into terrain shader types and how they affect visual appearance.',
    author: null,
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://wiki.faforever.com/en/Development/Shaders/terrain-shaders',
  },
  {
    id: 'g15',
    category: 'terrain',
    status: 'available',
    title: 'Creating AI Friendly Maps',
    abstract: 'Design principles and technical requirements for maps that play well with the AI.',
    author: null,
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://wiki.faforever.com/en/Development/Mapping',
  },
  {
    id: 'g16',
    category: 'terrain',
    status: 'available',
    title: 'Making Bad Maps Better',
    abstract: 'Before/after examples showing how to improve weak map designs.',
    author: 'Biass',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://forum.faforever.com',
  },
  {
    id: 'g17',
    category: 'terrain',
    status: 'available',
    title: 'What Makes a Bad Map?',
    abstract: 'Video analysis of common map design mistakes and how to avoid them.',
    author: 'TheDuelist',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: null,
    _urlPending: true,
  },
  {
    id: 'g18',
    category: 'terrain',
    status: 'available',
    title: 'Understanding Team Maps',
    abstract: 'Team map balance — expansion, chokepoints and fair starts.',
    author: null,
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://forum.faforever.com/topic/180',
  },
  {
    id: 'g19',
    category: 'terrain',
    status: 'available',
    title: "Moses' Tips for Team Map Design",
    abstract: 'Practical tips from experienced team map designer Moses.',
    author: 'Moses',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://forum.faforever.com/topic/322',
  },

  // ── Gaea ─────────────────────────────────────────────────────────────────────
  {
    id: 'g20',
    category: 'gaea',
    status: 'available',
    title: 'Introduction',
    abstract: 'What Gaea is, why it is used for FA mapping and how it fits into the overall workflow.',
    author: null,
    thumb: null,
    htmlFile: 'gaea/gaea-introduction.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g21',
    category: 'gaea',
    status: 'available',
    title: 'Gaea Basics',
    abstract: 'Core concepts of the Gaea node graph — key nodes, build settings and exporting heightmaps.',
    author: null,
    thumb: null,
    htmlFile: 'gaea/gaea-basics.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g22',
    category: 'gaea',
    status: 'available',
    title: 'Terrain Masks',
    abstract: 'Creating and exporting terrain masks in Gaea for use as stratum and splat layers in the FAF editor.',
    author: null,
    thumb: null,
    htmlFile: 'gaea/gaea-masks.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g23',
    category: 'gaea',
    status: 'available',
    title: 'Texturing',
    abstract: 'Texture workflow in Gaea — generating stratum masks and albedo maps for in-engine use.',
    author: null,
    thumb: null,
    htmlFile: 'gaea/gaea-texturing.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g24',
    category: 'gaea',
    status: 'available',
    title: 'Map-Wide Assets',
    abstract: 'Generating and applying map-wide albedo, normal and shadow decals using Gaea.',
    author: null,
    thumb: null,
    htmlFile: 'gaea/gaea-mapwide-assets.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g24a',
    category: 'gaea',
    status: 'available',
    title: 'Custom Textures',
    abstract: 'Importing and using custom textures inside Gaea — file requirements, colour spaces and node setup.',
    author: null,
    thumb: null,
    htmlFile: 'gaea/gaea-custom-textures.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g24b',
    category: 'gaea',
    status: 'available',
    title: 'Full Workflow',
    abstract: 'End-to-end Gaea workflow — from initial terrain setup through masks, texturing and final export.',
    author: null,
    thumb: null,
    htmlFile: 'gaea/gaea-workflow.html',
    videoUrl: null,
    externalUrl: null,
  },

  // ── Water ─────────────────────────────────────────────────────────────────────
  {
    id: 'g25',
    category: 'water',
    status: 'available',
    title: 'Overview & Elevation',
    abstract: 'How the water system works, fidelity levels, enabling water and the three elevation values.',
    author: 'Jip',
    thumb: null,
    htmlFile: 'water/water-overview.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g26',
    category: 'water',
    status: 'available',
    title: 'Color & Refraction',
    abstract: 'Surface color, color lerp, refraction scale and the water ramp texture.',
    author: 'Jip',
    thumb: null,
    htmlFile: 'water/water-color-refraction.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g27',
    category: 'water',
    status: 'available',
    title: 'Reflections & Fresnel',
    abstract: 'Sky cubemap, unit reflections, Fresnel blending — and which parameters are actually unused.',
    author: 'Jip',
    thumb: null,
    htmlFile: 'water/water-reflections.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g28',
    category: 'water',
    status: 'available',
    title: 'Sun & Specular',
    abstract: 'Sun direction, color, shininess — and the difference between legacy Blinn-Phong and the new PBR mode.',
    author: 'Jip',
    thumb: null,
    htmlFile: 'water/water-sun.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g29',
    category: 'water',
    status: 'available',
    title: 'Wave Textures & Normal Layers',
    abstract: 'The four wave normal layers, repeat rates, scroll directions and available engine textures.',
    author: 'Jip',
    thumb: null,
    htmlFile: 'water/water-waves.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g30',
    category: 'water',
    status: 'available',
    title: 'Wave Generators',
    abstract: 'Placed wave emitters for localized shoreline and turbulence effects — all parameters explained.',
    author: 'Jip',
    thumb: null,
    htmlFile: 'water/water-generators.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g31',
    category: 'water',
    status: 'available',
    title: 'Water Masks',
    abstract: 'UtilityTextureC channels, foam mask, flatness mask, depth bias mask and waterMap.dds.',
    author: 'Jip',
    thumb: null,
    htmlFile: 'water/water-masks.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g33',
    category: 'water',
    status: 'available',
    title: 'Generating Clouds',
    abstract: 'How to generate and configure dynamic cloud layers for atmosphere.',
    author: 'Jip',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://forum.faforever.com/topic/',
    _urlPending: true,
  },

  // ── Decals ────────────────────────────────────────────────────────────────────
  {
    id: 'g34',
    category: 'decals',
    status: 'available',
    title: 'Introduction to Decals',
    abstract: 'This Guide covers what decals are, why they matter for map quality, and how the two decal types — albedo and normal map — work together to turn a flat, repetitive terrain into a believable surface.',
    author: 'Seraphim-Noob',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: null,
    seriesPart: 1, seriesTotal: 5, seriesName: 'About Decals',
  },
  {
    id: 'g35',
    category: 'decals',
    status: 'available',
    title: 'Converting Normal Maps',
    abstract: 'Converting and preparing normal maps for use as decals in FA maps.',
    author: 'Jip',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://forum.faforever.com/topic/245',
    seriesPart: 2, seriesTotal: 5, seriesName: 'About Decals',
  },
  {
    id: 'g36',
    category: 'decals',
    status: 'available',
    title: 'WorldMachine Templates',
    abstract: 'Using WorldMachine templates to generate decal textures for terrain detail.',
    author: 'Jip',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: null,
    _urlPending: true,
    seriesPart: 3, seriesTotal: 5, seriesName: 'About Decals',
  },
  {
    id: 'g37',
    category: 'decals',
    status: 'available',
    title: 'Generating Map-Wide Normal Texture',
    abstract: 'Creating a map-wide normal texture decal for cohesive terrain detail.',
    author: 'Jip',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: null,
    _urlPending: true,
    seriesPart: 4, seriesTotal: 5, seriesName: 'About Decals',
  },
  {
    id: 'g38',
    category: 'decals',
    status: 'available',
    title: 'Generating Map-Wide Lighting Texture',
    abstract: 'Baking and applying a map-wide lighting/shadow texture as a decal.',
    author: 'Jip',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://forum.faforever.com/topic/786',
    seriesPart: 5, seriesTotal: 5, seriesName: 'About Decals',
  },
  {
    id: 'g39',
    category: 'decals',
    status: 'available',
    title: 'Custom Decals and Stratums',
    abstract: 'Creating and using fully custom decals and stratum textures.',
    author: 'Jip',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: null,
    _urlPending: true,
  },

  // ── AI & Markers ──────────────────────────────────────────────────────────────
  {
    id: 'g40',
    category: 'ai',
    status: 'available',
    title: 'AI Markers',
    abstract: 'Types of AI markers, their roles and how to place them correctly.',
    author: 'Jip',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://forum.faforever.com/topic/145',
    seriesPart: 1, seriesTotal: 2, seriesName: 'About Markers',
  },
  {
    id: 'g41',
    category: 'ai',
    status: 'available',
    title: 'Movement & Pathing Markers',
    abstract: 'Configuring movement and pathing markers for robust AI navigation.',
    author: 'Jip',
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://forum.faforever.com/topic/343',
    seriesPart: 2, seriesTotal: 2, seriesName: 'About Markers',
  },

  // ── Adaptive Maps ─────────────────────────────────────────────────────────────
  {
    id: 'g42',
    category: 'adaptive',
    status: 'available',
    title: 'Adaptive Maps Overview',
    abstract: 'Introduction to adaptive maps — what they are and how the scripting system works.',
    author: null,
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://wiki.faforever.com/en/Development/Mapping/Adaptive-Maps',
  },
  {
    id: 'g43',
    category: 'adaptive',
    status: 'available',
    title: 'Adaptive Mapping Guide 2021',
    abstract: 'Comprehensive guide to creating adaptive maps with the 2021 scripting framework.',
    author: null,
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://wiki.faforever.com/en/Development/Mapping/Adaptive-Mapping-2021',
  },

  // ── Skybox ────────────────────────────────────────────────────────────────────
  {
    id: 'g44',
    category: 'skybox',
    status: 'available',
    title: 'Skybox Overview',
    abstract: 'Introduction to the skybox system — what it controls and how the individual layers work together.',
    author: null,
    thumb: null,
    htmlFile: 'skybox/skybox-overview.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g44a1',
    category: 'skybox',
    status: 'available',
    title: 'Architecture',
    abstract: 'Understanding and configuring the architecture of a skybox.',
    author: null,
    thumb: null,
    htmlFile: 'skybox/skybox-architecture.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g44a',
    category: 'skybox',
    status: 'available',
    title: 'Atmosphere',
    abstract: 'Configuring the atmospheric gradient, horizon color and sky dome appearance.',
    author: null,
    thumb: null,
    htmlFile: 'skybox/skybox-atmosphere.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g44b',
    category: 'skybox',
    status: 'available',
    title: 'Cirrus Clouds',
    abstract: 'Adding and tuning high-altitude cirrus cloud layers — texture, speed, density and color.',
    author: null,
    thumb: null,
    htmlFile: 'skybox/skybox-cirrus.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g44c',
    category: 'skybox',
    status: 'available',
    title: 'Planets & Moons',
    abstract: 'Placing and configuring planet and moon objects in the skybox — position, scale and texture.',
    author: null,
    thumb: null,
    htmlFile: 'skybox/skybox-planets.html',
    videoUrl: null,
    externalUrl: null,
  },

  // ── Co-op & Campaign ──────────────────────────────────────────────────────────
  {
    id: 'g46',
    category: 'coop',
    status: 'available',
    title: 'Introduction',
    abstract: 'Reference list of maps approved and ready for use in campaign and co-op content.',
    author: null,
    thumb: null,
    htmlFile: 'Campaign/Introduction.html',
    videoUrl: null,
    externalUrl: null,
  },
  {
    id: 'g46.1',
    category: 'coop',
    status: 'available',
    title: 'The Map-Script',
    abstract: 'Reference list of maps approved and ready for use in campaign and co-op content.',
    author: null,
    thumb: null,
    htmlFile: 'Campaign/Script.html',
    videoUrl: null,
    externalUrl: null,
  },
    {
    id: 'g46.2',
    category: 'coop',
    status: 'available',
    title: 'Creating AI',
    abstract: 'Reference list of maps approved and ready for use in campaign and co-op content.',
    author: null,
    thumb: null,
    htmlFile: 'Campaign/creating_ai.html',
    videoUrl: null,
    externalUrl: null,
  },
  // ── Vault & Standards ─────────────────────────────────────────────────────────
  {
    id: 'g47',
    category: 'vault',
    status: 'available',
    title: 'Vault Rules',
    abstract: 'Official FAF Vault submission rules — file requirements, naming conventions and quality standards.',
    author: null,
    thumb: null,
    htmlFile: null,
    videoUrl: null,
    externalUrl: 'https://wiki.faforever.com/en/VaultRules',
  },
      {
    id: 'g49',
    category: 'gameplay',
    status: 'available',
    title: 'Map Size',
    abstract: 'Getting Started covers everything you need to go from zero to a running editor. You will learn where to download the editor, how to install it, and what each setting in the Preferences menu does. By the end of this section, your editor is fully configured and ready to use.',
    author: 'Seraphim-Noob',
    thumb: null,
    htmlFile: 'gameplay/mapsize.html',
    videoUrl: null,
    externalUrl: null,
  },
];


// ── Helpers ───────────────────────────────────────────────────────────────────

/** All guides in a given category. */
export const getGuidesByCategory = (categoryId) =>
  GUIDES.filter(g => g.category === categoryId);

/** Single category by id. */
export const getCategoryById = (id) =>
  GUIDE_CATEGORIES.find(c => c.id === id);

/** Single guide by id. */
export const getGuideById = (id) =>
  GUIDES.find(g => g.id === id);

/** All unique authors across all guides (excluding null). */
export const getAllAuthors = () =>
  [...new Set(GUIDES.map(g => g.author).filter(Boolean))].sort();

/** All guides that still need a URL filled in. */
export const getPendingGuides = () =>
  GUIDES.filter(g => g._urlPending);

/** Search all guides across all categories — title + abstract + author. */
export const searchGuides = (query) => {
  if (!query || !query.trim()) return [];
  const q = query.trim().toLowerCase();
  return GUIDES.filter(g =>
    g.title?.toLowerCase().includes(q) ||
    g.abstract?.toLowerCase().includes(q) ||
    g.author?.toLowerCase().includes(q)
  );
};
